import type { Metadata } from 'next';
import './globals.css';
import FixThemeProvider from '../components/ThemeToggler/FixThemeProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<meta name='theme-color' content='' />
			<body className={`antialiased`}>
				<FixThemeProvider>{children}</FixThemeProvider>
			</body>
		</html>
	);
}
